name: Build AMI using Packer

env:
  PACKER_BUILD_ARGS: -timestamp-ui -on-error=cleanup
  PACKER_TEMPLATE_DIR: ./packer
  AWS_DEFAULT_REGION: eu-west-1
  BUILD_DEPENDENCIES: packer

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-packer:
    runs-on: ubuntu-latest
    name: validate packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update & Install build dependencies
        run: sudo apt update && sudo apt install ${{ env.BUILD_DEPENDENCIES }}

      - name: validate template 
        run: packer validate ${{ env.PACKER_TEMPLATE_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          vpc_id: ${{ secrets.AWS_VPC_ID }}
          subnet_id: ${{ secrets.AWS_SUBNET_ID }}

  build-ami:
    runs-on: ubuntu-latest
    name: build AMI
    needs: validate-packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update & Install build dependencies
        run: sudo apt update && sudo apt install ${{ env.BUILD_DEPENDENCIES }}

      - name: Build AMI
        run: packer build ${{ env.PACKER_BUILD_ARGS }} ${{ env.PACKER_TEMPLATE_DIR }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          vpc_id: ${{ secrets.AWS_VPC_ID }}
          subnet_id: ${{ secrets.AWS_SUBNET_ID }}

